#ifndef MENU_GUARD
#define MENU_GUARD

const char *MenuString=
"-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.\n"
"----------------------------------------------------------------------\n"
"	    :::::::::   ::::::::  ::::    :::  ::::::::  \n"
"	    :+:    :+: :+:    :+: :+:+:   :+: :+:    :+: \n"
"	    +:+    +:+ +:+    +:+ :+:+:+  +:+ +:+        \n"
"	    +#++:++#+  +#+    +:+ +#+ +:+ +#+ :#:        \n"
"	    +#+        +#+    +#+ +#+  +#+#+# +#+   +#+# \n"
"	    #+#        #+#    #+# #+#   #+#+# #+#    #+# \n"
"	    ###         ########  ###    ####  ########\n"
"______________________________________________________________________\n"
"_._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._.\n"
" \n"
"	                 * * * * * * * * * *\n"
"	                 * [S]ingle player *\n"
"	                 *  [M]ultiplayer  *\n"
"	                 *    [R]esume     *\n"
"	                 *   Se[t]tings    *\n"
"	                 *  [H]ighscores   *\n"
"	                 * [I]nstructions  *\n"
"	                 *    [A]bout      *\n"
"	                 *     [E]xit      *\n"
"	                 * * * * * * * * * *\n";
const char *SettingsString=
"-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.\n"
"----------------------------------------------------------------------\n"
"       		    _   _  _)_ _)_ o  _   _    _ \n"
"       		   (   )_) (_  (_  ( ) ) (_(  (  \n"
"       		   _) (_                   _) _) \n"
"______________________________________________________________________\n"
"_._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._.\n"
" \n \n \n \n"
"	                 * * * * * * * * * *\n"
"	                 *   AI Settings:  *\n"
"	                 *     [S]mart     *\n"
"	                 *    S[t]upid     *\n"
"	                 *      Mode:      *\n"
"	                 * Single [P]layer *\n"
"	                 *  [M]ultiplayer  *\n"
"	                 * [E]pilepsy mode *\n"
"	                 *                 *\n"
"	                 * Start [n]ew game*\n"
"	                 *  [Q]uit to menu *\n"
"	                 * * * * * * * * * *\n";
const char *InstructionsString=
"-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.\n"
"----------------------------------------------------------------------\n"
"      888             w                    w   w                  \n"
"       8  8d8b. d88b w8ww 8d8b 8   8 .d8b w8ww w .d8b. 8d8b. d88b \n"
"       8  8P Y8 `Yb.  8   8P   8b d8 8     8   8 8' .8 8P Y8 `Yb. \n"
"      888 8   8 Y88P  Y8P 8    `Y8P8 `Y8P  Y8P 8 `Y8P' 8   8 Y88P \n"
"______________________________________________________________________\n"
"_._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._.\n"
" \n \n"
"                  Really ? You are that desperate ?"
" \n \n \n"
"                  Anyway, you navigate through the menus \n"
"                  by tapping the letter surrounded by [] \n \n"
"                  The goal is to score the most points  \n"
"                  possible \n \n"
"                  Player 1 controls:\n"
"                               w - move up \n"
"                               s - move down \n \n"
"                  Player 2 controls:\n"
"                               i - move up \n"
"                               k - move down \n \n"
"                  Additional controls:\n"
"                               p - pause \n"
"                               q - back to main menu \n \n"
"	                 * * * * * * * * * *\n"
"	                 *  [Q]uit to menu *\n"
"	                 * * * * * * * * * *\n";
const char *AboutString=
"-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.\n"
"----------------------------------------------------------------------\n"
"                       d8b                               \n"
"                       ?88                          d8P  \n"
"                        88b                      d888888P\n"
"             d888b8b    888888b  d8888b ?88   d8P  ?88'  \n"
"            d8P' ?88    88P `?8bd8P' ?88d88   88   88P   \n"
"            88b  ,88b  d88,  d8888b  d88?8(  d88   88b   \n"
"            `?88P'`88bd88'`?88P'`?8888P'`?88P'?8b  `?8b  \n"
"______________________________________________________________________\n"
"_._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._.\n"
" \n \n"
"                  This game was brought to you by:"
" \n \n"
"                  Kaloyan Darmonev - lead programmer \n"
"                  Emilian Stankov - additional programming \n"
"                  Emilian Stankov - ASCII ""\"""art""\"\n"
"                  Emilian Stankov - background music \n \n"
"                  But most importantly, this project would \n"
"                  not be made without the moral support of:  \n \n"
"                  Sophia Petrova - lead moral supporter \n"
"                  Le Hoang Tung - aditional moral support \n \n"
"	                 * * * * * * * * * *\n"
"	                 *  [Q]uit to menu *\n"
"	                 * * * * * * * * * *\n";
const char *Boundaries =
"______________________________________________________________________ \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"                                   | \n"
"___________________________________|__________________________________";
#endif
